name: Contributors

on:
    schedule:
        - cron: "0 0 * * 0" # Every Sunday at midnight
    workflow_dispatch: # Allow manual trigger

jobs:
    contributors:
        name: Update contributors
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v5
            - uses: akhilmhdh/contributors-readme-action@v2.3.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  image_size: 80
                  columns_per_row: 6
                  readme_path: README.md
